// Headers ==============================================================================

#include "../Namuh_Main_H.h"
string BuildDate =  std::string(__TIME__) + " " + std::string(__DATE__) ;
// CPP ==============================================================================

#include "../Itoa.cpp"
#include "../Amnesic Faune manager.cpp"
#include "../ArcEnBois.cpp"
#include "../Atmosphere manager.cpp"
#include "../Carried Weapon.cpp"
#include "../Construction Manager.cpp"
#include "../ConstructionElement.cpp"
#include "../ConstructionRigidElement.cpp"
#include "../Construction.cpp"
#include "../DeathMatchRules.cpp"
#include "../Faune Entity.cpp"
#include "../Faune manager.cpp"
#include "../File_Serialiser.cpp"
#include "../Graph.cpp"
#include "../GraphAxis.cpp"
#include "../GUI.cpp"
#include "../GUI_FPS.cpp"
#include "../GUI_MainMenu.cpp"
#include "../GUI_MainMenu_Handlers_PlayerProfile.cpp"
#include "../GUI_Sandbox.cpp"
#include "../GUI_Sandbox_Handlers_CreateLink.cpp"
#include "../GUI_Sandbox_Handlers_LoadFile.cpp"
#include "../GUI_Sandbox_Handlers_Main.cpp"
#include "../GUI_Sandbox_Handlers_SaveFileAs.cpp"
#include "../HDR.cpp"
#include "../Hydrax Manager.cpp"
#include "../Javelot.cpp"
#include "../Lance Pierre.cpp"
#include "../Live Debugger.cpp"
#include "../Main Menu Background.cpp"
#include "../main.cpp"
#include "../Map Loader.cpp"
#include "../Map Parser.cpp"
#include "../Menu circulaire.cpp"
#include "../Mesh Generator.cpp"
#include "../Ogre initialisation.cpp"
#include "../Paged geometry Manager.cpp"
#include "../Partie.cpp"
#include "../personnage.cpp"
#include "../PhysX Manager.cpp"
#include "../PhysX_raft.cpp"
#include "../PhysX_hide.cpp"
#include "../PhysX_Trunk.cpp"
#include "../PhysX_Menhir.cpp"
#include "../PhysX_Disk.cpp"
#include "../PhysX_trampoline.cpp"
#include "../PhysX_Wings.cpp"
#include "../PhysX_Waterfall.cpp"
#include "../Player Profile Manager.cpp"
#include "../Projectile.cpp"
#include "../Raknet Client.cpp"
#include "../Raknet Manager.cpp"
#include "../Raknet Server.cpp"
#include "../Sandbox_Constructeur.cpp"
#include "../Saveable.cpp"
#include "../System.cpp"
#include "../Vie HUD.cpp"